

export default function TermsConditions() {
  return (
    <div className="w-full min-h-screen bg-gradient-to-br from-[#DAFCFF] via-[#EFF2FF] to-[#F2D9E6]">

      {/* Top Header Bar */}
      <div className="bg-[#183C8B] h-2 md:h-3 w-full"></div>

      {/* Page Title */}
      <div className="text-center" style={{ paddingBottom: '20px' }}>
        <div className="bg-white shadow-md py-3 md:py-4 px-4 sm:px-6 flex justify-center items-center">
          <h1 className="text-xl sm:text-2xl md:text-3xl lg:text-4xl font-bold text-[#2A66C4]">
            Terms-&-Conditions
          </h1>
        </div>
      </div>

      {/* Content Wrapper */}
      <div className="max-w-fullmx-auto px-4 sm:px-6 space-y-10 md:space-y-16 text-black" style={{ padding: '20px' }}>
        {/* Section */}
        <section>
          <h2 className="text-lg sm:text-xl md:text-2xl lg:text-3xl font-semibold mb-3 text-center">
            Terms of Use of Service – VYRALAI
          </h2>
          <p className="text-sm sm:text-base md:text-lg leading-7 md:leading-8">
            Customer understands, acknowledges, and agrees that these Terms and Conditions (“Terms”), are made as a part of the [VYRALAI All-in-One Digital Marketing Platform], which governs the access and use of the Service (as defined below) provided by VYRALAI Digital Solutions Pvt. Ltd. (“Company”), an Indian company with a principal place of business located at 28-29, C.K.Park, Surat, Gujarat, India. By opening an Account or otherwise using the Service, the Customer affirms its consent to these Terms. If a Customer is acting on behalf of or for the benefit of a corporate entity or other third party, Customer represents and warrants that it has the necessary authority to agree to these Terms and to bind such corporate entity or third party to these Terms.
          </p>
        </section>

        {/* Section */}
        <section>
          <h2 className="text-lg sm:text-xl md:text-2xl lg:text-3xl font-semibold mb-3 text-center">
            Definitions
          </h2>
          <p className="text-sm sm:text-base md:text-lg leading-7 md:leading-8">
            1. “Affiliate” of an entity means a corporation that is controlling, controlled by, or under common control, of an entity.<br />
            2. “Ad Account” means the account of the Customer/AdKrity in the Ad Network.<br />
            3. “Ad Network” means that advertisement platform on for which the Ad Account relates and with respect to which the Services are rendered, such as Facebook, Google and so on.<br />
            4. “Ad Spend” means that total amount included in all Ad Accounts of a Customer , regardless if such amount was utilized to the fullest extent or not.<br />
            5. “Platform” means the Company’s proprietary platform for management, planning, optimizing, monitoring and execution of advertising strategies and related activities and which is intended to provide the Service to the Customer. The Platform includes, inter alia, an application, database, various software, servers, and also including any changes, updates, upgrades, modifications and enhancements made thereto, and any related modules, addons, tools, browser plugins and applications as well as any documentation relating thereto.<br />
            6. “Intellectual Property Rights” shall mean, all rights arising from patents, copyrights, trade secrets, Confidential Information, trademarks, service marks, trade names, mask works, applications and other proprietary rights in any jurisdiction, to all (i) inventions, discoveries, works of authorship, know-how, technical information, work product, designs, ideas, concepts, innovations, drawings, schematics, original works of authorship, formulae, concepts, techniques, know how, methods, systems, processes, compositions of matter, computer software programs, databases,(ii)  any improvements, enhancements or modifications related thereto, all the foregoing. <br />
            7. “Service” means the Mobile Application available as a “Software as a Service” (SaaS) basis. <br />
            8. “Customer Data” means any data, information, or material provided by Customer to Company in connection with the Service, including but not limited to any data, information, or material that is inputted into the Service by Customer or on Customer’s behalf, and any data, information, or material that is generated by the Service as a result of Customer’s use of the Service.
          </p>
        </section>
        <section>
          <h2 className="text-lg sm:text-xl md:text-2xl lg:text-3xl font-semibold text-center pb-4">
            License; Use of Service
          </h2>
          <p className="text-sm sm:text-base md:text-lg leading-7 md:leading-8 pb-20 md:pb-40">
            The Service is a SaaS advertising tools and documentation provided by the Company and may be used by the Customer through the Mobile Application. The Service is intended to assist in the creation, management, monitoring, execution and optimization of advertising campaigns on the applicable Ad Networks but is not intended to replace Customer’s discretion. In addition, marketing effectiveness is affected by a multitude of factors, such as such Ad Networks conduct and compliance, product quality and marketing strategies selected by the Customer. Therefore, Company does not warrant or guarantee any results of a campaign or from the use of the Service will meet Customer’s expectations or requirements or produce profit. It is acknowledged by the Customer that the Services largely depended on the availability and operation of third-party platforms and websites, including, without limitation, the applicable Ad Networks and that the Company shall not bear responsibility or liability with respect to such, their operation, rules, functionalities and/or changes made thereto.
            Company continuously is working on adding improving the features of the Services, and may do so in its discretion, and as part of such, Company may also remove certain function which are not frequently used or are replaced by other functions. There is no guarantee by the Company to maintain certain features and Customer acknowledges that current features available in the Platform are subject to change by the Company in its discretion.
            Customer is required to obtain and maintain any telecommunication or networking services or equipment, security services or systems, or hardware or other equipment for accessing the Platform. Company does not offer such, and if Customer requires any of the foregoing, Customer must obtain such means at its own expense. Company does not make any warranty with respect to such means.
            The Service may only be used for the purpose indicted above ("Purpose"). The Platform and the Service may not be used, copied, reproduced, distributed, transmitted, broadcasted, displayed, sold, licensed, or otherwise exploited for any other purpose whatsoever without the prior written consent of the Company. Company reserves all rights in and to the Platform and the Service.
            In consideration of the fees, and subject to the other terms and conditions hereof, Company grants to the Customer, during the Term, a non-exclusive, non-transferable, revocable, right to access and use Service and access the Platform under these Terms.
            Customer may not use the Service for any of the following purposes including without limitation managing campaigns promoting or supporting any of the following purposes (the "Prohibited Activities") and the Company disclaims any and all liabilities, losses and or damages with respect to any use of the Services which constitutes a Prohibited Activity: (a) Engaging in unlawful, indecent, obscene or other morally objectionable activities; (b) Disseminating any unlawful, harassing, abusive, threatening, harmful, vulgar, obscene or   otherwise objectionable or illegal materials; (c) Transmitting material that encourages conduct which may constitute a criminal offence, result in civil liability or otherwise breaches any relevant law, regulation and/or code of practice; (d) Gaining unauthorized access to other computer systems; (e) Interfering with any other person's use of the Service and/or using the Services to provide services to third parties which are similar to the Services (or parts thereof); (f) Transmitting, junk mail, chain letters or "spam"; (g) Making and/or transferring and/or storing electronic copies of materials protected by copyright without the express permission of the owner of the material, or otherwise making such use of the Service that infringes third parties intellectual property rights; (h) Circumvent, disable or otherwise interfere with security related features or other features of the Platform and/or with the use of Services, or enforce any limitations on use of the Platform and/or the Services; and (i) transmitting materials or otherwise acting (or failing to act) in breach of the terms and condition of any applicable Ad Network.

          </p>
        </section>

        <section>
          <h2 className="text-lg sm:text-xl md:text-2xl lg:text-3xl font-semibold text-center pb-4">
            Registration
          </h2>
          <p className="text-sm sm:text-base md:text-lg leading-7 md:leading-8 pb-20 md:pb-40">
            Access to the Platform and the Service requires the signup of the Customer, As part of the signup process, the Customer shall be required to link certain Ad Accounts. The Customer may, from time to time, remove or add Ad Accounts in its discretion.
            Access to the Platform is permitted only by a phone number to the Customer. The credentials are to be kept confidential and personal and may not be disclosed or used by any other person except the Customer for which they were generated.
            Except as expressly permitted by these Terms, or specifically authorized in writing and in advance by Company, Customer shall not, nor permit others to: (a) use, copy, modify, create derivative works from or distribute the Service and/or the Platform, any part thereof, or any copy, adaptation, transcription, or merged portion thereof, in any way other then as agreed herein; (b) decode, reverse engineer, disassemble, decompile or otherwise translate or convert the Service and/or the Platform; (c) transfer, loan, lease, assign, rent, or otherwise sublicense the rights granted hereunder in any way other then as permitted under these Terms; or (c) remove any copyright, proprietary or similar notices from the Platform or any documentation thereof (or any copies thereof).
          </p>
        </section>

        <section>
          <h2 className="text-lg sm:text-xl md:text-2xl lg:text-3xl font-semibold text-center pb-4">
            Intellectual Property
          </h2>
          <p className="text-sm sm:text-base md:text-lg leading-7 md:leading-8 pb-20 md:pb-40">
            Customer acknowledges and agrees that all proprietary and/or Intellectual Property Rights in and to the Service and/or to the Platform or anything related thereto, and all documentation, including without limitation all inventions, patent, patent application, copyright, registered design, trademark, trade dress or other industrial property right in respect thereto, as well as any Confidential Information, belong to the Company alone. This Agreement does not transfer ownership of the Platform or underlying technology or any part thereof.
            Any Intellectual Property Rights in and to any content made by the Customer or on its behalf shall be the sole property of the Customer and its assignees. However, any feedback, advises or comments received by the Company from the Customer or any other user, which relates to the Platform and/or the Service shall be deemed to be property of the Company and if required, shall be fully assigned to the Company without consideration.
            It is clarified that the Customer acknowledges that any Intellectual Property Rights belonging to the Ad Network, whether by virtue of law or the terms and conditions applicable to such Ad Network shall belong to the Ad Network.
          </p>
        </section>
      </div>
    </div>
  );
}
